### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by bigant88** [kevinselwyn/pokestop#1]
python pokestop.py --latitude 13.74685 --longitude 100.5391 
Traceback (most recent call last):
  File "pokestop.py", line 336, in <module>
    main()
  File "pokestop.py", line 328, in main
    pokestop = Pokestop(vars(args))
  File "pokestop.py", line 71, in **init**
    self.version = self.get_version()
  File "pokestop.py", line 88, in get_version
    return re.findall(r'gen_dashboard_(\w*).js', request.text)[0]
IndexError: list index out of range

**Comment by kevinselwyn** [comment]
Looks like you just needed to revalidate. Added an error message to let the user know.
